In [1]:
import requests
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [2]:
url='https://fakestoreapi.com/products'
res=requests.get(url)
res1=res.json()
df=pd.DataFrame(res1)
df.head()

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"

In [3]:
def data_fetch_api():
    url='https://fakestoreapi.com/products'
    res=requests.get(url)
    res1=res.json()
    df=pd.DataFrame(res1)
    df['rate']=df['rating'].map(lambda x:x['rate'])
    df['count']=df['rating'].map(lambda x:x['count'])
    df=df[['id','title','price','category','rate','count']]
    return df

In [4]:
df=data_fetch_api()

In [5]:
df

,id,title,price,category,rate,count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing,3.9,120
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing,4.1,259
2,3,Mens Cotton Jacket,55.99,men's clothing,4.7,500
3,4,Mens Casual Slim Fit,15.99,men's clothing,2.1,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.6,400
5,6,Solid Gold Petite Micropave,168.00,jewelery,3.9,70
6,7,White Gold Plated Princess,9.99,jewelery,3.0,400
7,8,Pierced Owl Rose Gold Plated Stainless Steel D...,10.99,jewelery,1.9,100
8,9,WD 2TB Elements Portable External Hard Drive -...,64.00,electronics,3.3,203
9,10,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,109.00,electronics,2.9,470
10,11,Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...,109.00,electronics,4.8,319
11,12,WD 4TB Gaming Drive Works with Playstation 4 P...,114.00,electronics,4.8,400
12,13,Acer SB220Q bi 21.5 inches Full HD (1920 x 108...,599.00,electronics,2.9,250
13,14,Samsung 49-Inch CHG90 144Hz Curved Gaming Moni...,999.99,electronics,2.2,140
14,15,BIYLACLESEN Women's 3-in-1 Snowboard Jacket Wi...,56.99,women's clothing,2.6,235
15,16,Lock and Love Women's Removable Hooded Faux Le...,29.95,women's clothing,2.9,340
16,17,Rain Jacket Women Windbreaker Striped Climbing...,39.99,women's clothing,3.8,679
17,18,MBJ Women's Solid Short Sleeve Boat Neck V,9.85,women's clothing,4.7,130
18,19,Opna Women's Short Sleeve Moisture,7.95,women's clothing,4.5,146
19,20,DANVOUY Womens T Shirt Casual Cotton Short,12.99,women's clothing,3.6,145

In [14]:
def Create_engine():
    engine=create_engine("mysql+pymysql://root:krishna123@localhost/price_monitor")
    return engine

In [15]:
def Data_store_db(df):
    conn=Create_engine()
    df.to_sql('product1',con=conn,if_exists='append',index=False)
    return 'Data Inserted'

In [16]:
Data_store_db(df)

'Data Inserted'

In [17]:
def price_fetch():
    dff=df['price']
    return dff

In [18]:
price_fetch()

0     109.95
1      22.30
2      55.99
3      15.99
4     695.00
5     168.00
6       9.99
7      10.99
8      64.00
9     109.00
10    109.00
11    114.00
12    599.00
13    999.99
14     56.99
15     29.95
16     39.99
17      9.85
18      7.95
19     12.99
Name: price, dtype: float64